### ISSUE TITLE
redirecting output to same file as is used for --merge results in an empty .tfstate file

### ISSUE THREAD

**Issue by dansteen** [dtan4/terraforming#113]
The following command will wipe out your .tfstate file:

terraforming rds --tfstate --merge ./terraform.tfstate > terraform.tfstate

The end result is an empty terraform.tfstate file.

**Comment by dtan4** [comment]
This behavior is by design of shell redirect, not a bug of Terraforming.

However it may be inconvenient not to overwrite existing tfstate at once, so I'm going to add `--overwrite` option. Please wait for next release :bow: 

## REF
- [Shell Command Language](http://pubs.opengroup.org/onlinepubs/009695399/utilities/xcu_chap02.html)

**Comment by dtan4** [comment]
I just released v0.2.0 with `--overwrite` option :shipit: Please try this.

If you still have something wrong, please reopen this issue!
