### ISSUE TITLE
When I use terraforming in Seoul region, I met the error .

### ISSUE THREAD

**Issue by delphinz** [dtan4/terraforming#411]
When I use terraforming in Seoul region, I met this  error ( Please see below)

> **" You are not subscribed to this service. Please go to http://aws.amazon.com to subscribe."** 

I can use terraforming in Tokyo region ,but I can't use in Seoul.
Do you have limit region?

**Comment by dtan4** [comment]
Terraforming itself doesn't have any region restriction.

I found this article:
https://aws.amazon.com/premiumsupport/knowledge-center/error-access-service/

> Resolve "You are not subscribed to this service" or "The AWS Access Key Id needs a subscription for the service" errors
> If you're using an account that was created in or after 2011, then update your account status.
> If you're using an account that was created before 2011, then update your pre-2011 account status.

It seems this issue is caused by your AWS account status, not by Terraforming. How about using another tool, such as awscli or Terraform?

If this issue still happens with Terraforming only, please reopen this issue. Thanks!
