### ISSUE TITLE
Support for ruby version 1.x

### ISSUE THREAD

**Issue by monicagangwar** [dtan4/terraforming#87]
There is no support for ruby version 1.x and its not even mentioned in the documentation

**Comment by dtan4** [comment]
Because of using some new features introduced by Ruby 2.x, Terraforming supports Ruby 2.x only.
I'm sorry for missing documentation, and I added "Supported version" section to README at https://github.com/dtan4/terraforming/commit/10c7a6ce86f5ad94e2f9dc21747e85e71fca890a .

Since [Ruby 1.x is no longer supported officially](https://www.ruby-lang.org/en/news/2015/02/23/support-for-ruby-1-9-3-has-ended/), I have no intension to adding Ruby 1.x support to Terraforming.
I strongly recommend to use Ruby 2.x or [Terraforming Docker Image](https://quay.io/repository/dtan4/terraforming) .
